runtime: nodejs12

module: test-app

env_variables:
  MY_NAME: "seungtaek"

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.8
  min_instances: 5
  max_instances: 10
  max_concurrent_requests: 50

handlers:
- url: /images
  static_dir: static/images
